account/urls.py
from django.urls import path
from django.contrib.auth.views import (logout, LoginView, logout_then_login, )

from account.views import RegisterView, Edit, edit
from . import views

app_name = 'account'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('activate/<code>/', views.activate_user_view, name='activate'),
    path('edit/', Edit.as_view(), name='edit'),
    path('logout_then_login/', logout_then_login, name='logout_then_login'),
    path('', views.dashboard, name='dashboard'),
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
]

images/urls.py
from django.urls import path

from images.views import ImageCreate, ImageDetail, ImageRanking, ImageDelete
from . import views


app_name = 'images'
urlpatterns = [
    path('create/', ImageCreate.as_view(), name='create'),
    path('detail/<int:id>/<slug:slug>/', ImageDetail.as_view(), name='detail'),
    path('like/', views.ImageLike.as_view(), name='like'),
    path('ranking/', ImageRanking.as_view(), name='ranking'),
    path('', views.image_list, name='list'),
    path('users_images/', views.users_image_list, name='users_image_list'),
    path('delete/<int:pk>/<slug:slug>/', ImageDelete.as_view(), name="delete_image"),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="header">
            <span class="logo"><a href="{% url 'dashboard' %}">Social Website</a></span>
            <ul class="menu">
                <li {% if section == "dashboard" %}class="selected"{% endif %}>
                    <a href="{% url 'dashboard' %}">My dashboard</a>
                </li>
                <li {% if section == "my images" %}class="selected"{% endif %}>
                    <a href="{% url 'images:users_image_list' %}">My images</a>
                </li>
                <li {% if section == "images" %}class="selected"{% endif %}>
                    <a href="{% url 'images:list' %}">Images</a>
                </li>
                <li {% if section == "people" %}class="selected"{% endif %}>
                    <a href="{% url 'account:user_list' %}">People</a>
                </li>
                <li {% if section == "ranking" %}class="selected"{% endif %}>
                    <a href="{% url 'images:ranking' %}">Most popular images</a>
                </li>
            </ul>
            <span class="user">
                {% if request.user.is_authenticated %}
                    Hello {{ request.user.first_name }} {{ request.user.last_name}},
                    <a href="{% url 'account:logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'account:login' %}">Login</a>
                {% endif %}
                {% if request.user.profile.photo %}
                    <img src="{{ request.user.profile.photo.url }}" alt="img" class="user-detail">
                {% endif %}
            </span>
        </div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                        <!--<a href="#" class="del-msg">x</a>-->
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>
        <script src="{% static 'js/close_message.js' %}"></script>
        <script>
            var csrftoken = $.cookie('csrftoken');
            function csrfSafeMethod(method) {
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken)
                    }
                }
            });
            $(document).ready(function(){
                {% block domready %}
                {% endblock %}
            });
        </script>
    </body>
</html>