images/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import ImageViewSet

router = routers.DefaultRouter()
router.register('images', ImageViewSet)

app_name = 'api-images'
urlpatterns = [
    path(r'', include(router.urls)),
]

images/urls.py
from django.urls import path

from images.views import ImageCreate, ImageDetail, ImageRanking, ImageDelete
from . import views


app_name = 'images'
urlpatterns = [
    path('create/', ImageCreate.as_view(), name='create'),
    path('detail/<int:id>/<slug:slug>/', ImageDetail.as_view(), name='detail'),
    path('like/', views.ImageLike.as_view(), name='like'),
    path('ranking/', ImageRanking.as_view(), name='ranking'),
    path('', views.image_list, name='list'),
    path('users_images/', views.users_image_list, name='users_image_list'),
    path('delete/<int:pk>/<slug:slug>/', ImageDelete.as_view(), name="delete_image"),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField(max_length=120, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.slug:
            self.slug = slugify(self.title)
            super().save()

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.pk, self.slug])

images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput
        }

    def clean_url(self):
        url = self.cleaned_data.get('url')
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match a valid image extension')
        return url

    def save(self, commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data.get('url')
        image_name = f'{slugify(image.title)}.{image_url.rsplit(".", 1)[1].lower()}'

        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)

        if commit:
            image.save()
        return image


class ImageUpdateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'description')

images/api/views.py
from rest_framework import viewsets
from .serializers import ImageSerializer
from ..models import Image


class ImageViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Image.objects.all()
    serializer_class = ImageSerializer

images/views.py
import redis
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.views.generic import CreateView, DetailView, UpdateView, ListView, View, DeleteView
from braces.views import JSONResponseMixin

from common import ajax_required
from actions.utils import create_action

from .forms import ImageCreateForm, ImageUpdateForm
from .models import Image


r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIST_PORT, db=settings.REDIS_DB)


@login_required
def image_create(request):
    if request.method == "POST":
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            create_action(request.user, 'bookmarked image', instance)
            messages.success(request, "Image added successfully")
            return redirect(instance.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)
    return render(request, 'images/create.html', {'section': 'images', 'form': form})


class ImageDelete(LoginRequiredMixin, DeleteView):
    model = Image
    success_url = reverse_lazy('images:list')

    def delete(self, request, *args, **kwargs):
        image = Image.objects.get(pk=kwargs['pk'], slug=kwargs['slug'])
        if self.request.user == image.user or self.request.user.is_staff:
            image.delete()
            return HttpResponseRedirect('/')
        else:
            raise PermissionDenied

class ImageCreate(LoginRequiredMixin, CreateView):
    model = Image

    def post(self, request, *args, **kwargs):
        form = ImageCreateForm(data=request.POST)

    def form_valid(self, form):
        cd = form.cleaned_data
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        create_action(self.request.user, 'bookmarked image', instance)
        messages.success(self.request, "Image added successfully")
        return redirect(instance.get_absolute_url())

    def get(self, request, *args, **kwargs):
        form = ImageCreateForm(data=request.GET)
        return render(request, 'images/create.html', {'section': 'images', 'form': form})


@login_required
def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    total_views = r.incr(f'image:{image.id}:views')
    r.zincrby(f'image_ranking', image.id, 1)
    return render(request, 'images/detail.html', {'section': 'image', 'image': image, 'total_views': total_views})


class ImageDetail(LoginRequiredMixin, DetailView):
    queryset = Image.objects.all()

    def get(self, request, *args, **kwargs):
        total_views = r.incr(f'image:{self.get_object().id}:views')
        r.zincrby(f'image_ranking', self.get_object().id, 1)
        return render(request, 'images/detail.html', {'section': 'image', 'image': self.get_object(), 'total_views': total_views})


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'liked image', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status': 'ok'})


class ImageLike(LoginRequiredMixin, JSONResponseMixin, View):

    def post(self, request, *args, **kwargs):
        image_id = request.POST.get('id')
        action = request.POST.get('action')
        if image_id and action:
            try:
                image = Image.objects.get(id=image_id)
                if action == 'like':
                    image.users_like.add(request.user)
                    create_action(request.user, 'liked image', image)
                else:
                    image.users_like.remove(request.user)
                return JsonResponse({'status': 'ok'})
            except:
                pass
        return JsonResponse({'status': 'ok'})


@login_required
def image_list(request):
    images = Image.objects.all().exclude(user=request.user)
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse("")
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'images/list_ajax.html', {'section': 'images', 'images': images})
    return render(request, 'images/list.html', {'section': 'images', 'images': images})


@login_required
def users_image_list(request):
    user = request.user
    images = Image.objects.filter(user=user)
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse("")
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'images/list_ajax.html', {'section': 'my images', 'images': images})
    return render(request, 'images/list.html', {'section': 'my images', 'images': images})


@login_required
def image_ranking(request):
    image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request, 'images/ranking.html', {"section": "ranking", "most_viewed": most_viewed})


class ImageRanking(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
        image_ranking_ids = [int(id) for id in image_ranking]
        most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
        most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
        return render(self.request, 'images/ranking.html', {"section": "ranking", "most_viewed": most_viewed})

templates/images/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}

{% block content %}
    <h1>Bookmark an image</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form action="." method="post">
            {{ form|crispy }}
            {% csrf_token %}
            <p><input type="submit" value="Bookmark it!"></p>
    </form>
{% endblock %}

templates/images/create_custom.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}

{% block content %}
    <h1>Create an image</h1>
    <form action="." method="post">
            {{ form|crispy }}
            {% csrf_token %}
            <p><input type="submit" value="Create it!"></p>
    </form>
{% endblock %}

templates/images/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ image.title }}{% endblock title %}

{% block content %}
    <h1>{{ image.title }}</h1>
    <h2>posted by <a href="{{ image.user.get_absolute_url }}">{{ image.user.get_full_name }}</a></h2>
    <a href="{% url 'images:update' pk=image.pk slug=image.slug %}">
        Update
    </a>
    <br>
    <br>
    {% thumbnail image.image "260" as im %}
        <a href="{{ im.url }}">
            <img src="{{ im.url }}" class="image-detail">
        </a>
    {% endthumbnail %}
    {% with total_likes=image.users_like.count users_like=image.users_like.all %}
        <div class="image-info">
            <div>
                <span class="count">
                    <span>{{ total_views }}</span> view{{ total_views|pluralize }}
                    <span class="total">{{ total_likes }}</span> like{{ total_likes|pluralize }}
                </span>
                <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like"
                   class="like button">
                    {% if request.user not in users_like %}
                        Like
                    {% else %}
                        Unlike
                    {% endif %}
                </a>
            </div>
            {{ image.description|linebreaks }}
        </div>
        <div class="image-likes">
            <h2>People who liked this post:</h2>
            {% for user in image.users_like.all %}
            <div>
                <a href="{{ user.get_absolute_url }}">
                    <img src="{{ user.profile.photo.url }}">
                    <p>{{ user.first_name }} {{ user.last_name }}</p>
                </a>
            </div>
            {% empty %}
                This image has no likes at the moment.
            {% endfor %}
        </div>
    {% endwith %}
{% endblock %}

{% block domready %}
    $('a.like').click(function(e){
        e.preventDefault();
        $.post("{% url 'images:like' %}",
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data){
                if(data['status'] == 'ok')
                {
                    var previous_action = $('a.like').data('action');

                $('a.like').data('action', previous_action == 'like' ?
    'unlike' : 'like');
                $('a.like').text(previous_action == 'like' ? 'Unlike' :
    'Like');
                var previous_likes = parseInt($('span.count .total').text());
                $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1)
                }
            }
        );
    });
{% endblock domready %}

templates/images/image_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}

{% block content %}
    <h1>Delete image</h1>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Yeap, I'm sure.</button>
    </form>
{% endblock %}

templates/images/image_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit your post{% endblock title %}

{% block content %}
    <h1>Edit your post:</h1>
    <p>You can edit your post using the following form:</p>

        <form action="." method="post">
            {{ form|crispy }}
            {% csrf_token %}
            <p><input type="submit" value="Save changes"></p>
        </form>
{% endblock %}

templates/images/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock %}

{% block content %}
    <h1>Images bookmarked </h1>
    <div id="image-list">
        {% include "images/list_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if ($(window).scrollTop() > margin && empty_page == false && block_request == false){
            block_request = true;
            page += 1;
            $.get('?page=' + page, function(data) {
                if(data == '') {
                    empty_page = true;
                }
                else {
                    block_request = false;
                    $('#image-list').append(data);
                }
            });
        }
    });
{% endblock %}

templates/images/list_ajax.html
{% load thumbnail %}

{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image "350x350" as im %}
                <a href="{{ image.get_absolute_url }}">
                    <img src="{{ im.url }}">
                </a>
            {% endthumbnail %}
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
                {{ image.title }}
            </a>
        </div>
        <li>{{ image.title }} - <a href="{% url 'images:delete_image' pk=image.pk slug=image.slug %}">Delete</a></li>
    </div>
{% endfor %}

templates/images/ranking.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}Image ranking{% endblock %}

{% block content %}
    <h1>Most popular images:</h1>
    <ol>
        {% for image in most_viewed %}
            <li>
                <a href="{{ image.get_absolute_url }}">
                    {{ image.title }}
                </a>
            </li>
        {% endfor %}
    </ol>
{% endblock %}